name: gitpush practice

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10]

    steps:
      
      - name: checkout
        uses: actions/checkout@v4
      
      
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow==2.10 numpy==1.21


      - name: run main
        run: python main.py
